[package]
name = "hello-rsocket"
version = "0.1.0"
authors = ["feuyeux <feuyeux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsocket_rust= "0.1.5"
bytes = "0.4.12"
futures = "0.1.29"
tokio = "0.1.22"