[package]
name = "hello-rsocket"
version = "0.1.0"
authors = ["feuyeux <feuyeux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsocket_rust = "0.3.0"
bytes = "0.5.2"
futures = "0.3.1"
tokio =  "0.2.2"